#!/bin/sh
# 
# Update bitnami banner htdocs if launched from launchpad
# Copyright 2016 Bitnami.com All Rights Reserved
#

. /opt/bitnami/scripts/init/functions

# when run with --force option, set the password regardless of flag
if [ "x$1" != "x--force" ] ; then
    run_once_globally_check "update_bitnami_banner_htdocs"
    if [ $? -ne 0 ]; then
        exit 0
    fi
fi

# get if password should be modified
PASSWD="`get_applications_password`"

if [ "x$PASSWD" = "x" ] ; then
  exit 0
fi

FILE=/opt/bitnami/apps/bitnami/banner/htdocs/index.html

if [ -f "$FILE" ] ; then
  sed 's,-- BEGIN DEFAULT PASSWORD --.,-- BEGIN DEFAULT PASSWORD,;s,..-- END DEFAULT PASSWORD,END DEFAULT PASSWORD,' -i $FILE
  sed 's,-- BEGIN CUSTOM PASSWORD,-- BEGIN CUSTOM PASSWORD -->,;s,END CUSTOM PASSWORD --,<!-- END CUSTOM PASSWORD --,' -i $FILE
else
  echo "Unable to find index.html file: $FILE"
fi